runtime: nodejs14

handlers:
- url: /favicon\.ico
  static_files: public/assets/favicon.ico
  upload: public/assets/favicon\.ico

- url: /static
  static_dir: public

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto